[package]
name = "erlang-port-examples"
version = "0.1.0"
authors = ["Duncan McGreggor <oubiwann@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
